CREATE TABLE PENSION (
AADHAR_NUMBER BIGINT NOT NULL,
NAME VARCHAR(255) NOT NULL,
DATE_OF_BIRTH VARCHAR(255) NOT NULL,
PAN VARCHAR(255) NOT NULL,
SALARY_EARNED BIGINT NOT NULL,
ALLOWANCES BIGINT NOT NULL,
SELF_PENSION BIGINT NOT NULL,	
FAMILY_PENSION BIGINT NOT NULL,
PENSION_TYPE VARCHAR(255) NOT NULL,
BANK_NAME VARCHAR(255) NOT NULL,
BANK_ACCOUNT_NUMBER BIGINT NOT NULL,
PRIMARY KEY(AADHAR_NUMBER)
);